### ISSUE TITLE
Scroller breaks SearchPanes show/hide toggle

### ISSUE THREAD

**Issue by fjf2002** [DataTables/SearchPanes#34]
This css rule from scroller:

```css
div.dts {
    display: block !important;
}
```

... overrides erroneously this rule from searchPanes:

```css
div.dtsp-hidden {
    display: none !important;
}
```

My workaround is:
```css
div.dts.dtsp-hidden {
    display: none !important;
}
```
